<?php

# $Id$

function shell_menu()
{
    $module = Oop_Core_ClassManager::getInstance()->getModule( 'shell' );
    return $module->addMenuItems( $module->addAdminSettingsMenu() );
}

function shell_adminForm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'shell' )->getAdminForm();
}

function shell_adminForm_validate( $form, &$formState )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'shell' )->validateAdminForm( $form, $formState );
}

function shell_show()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'shell' )->createModuleContent( 'show' );
}
