<?php

# $Id$

/**
 * Drupal 'help' hook
 * 
 * This function returns the help text for the admin/help# page. The label
 * returned must be placed in the module's lang file, in the 'lang/'
 * directory. It's the 'help' node of the 'system' section.
 * 
 * @param   string  The path for which to display help
 * @param   array   An array that holds the current path as would be returned from the arg() function
 * @return  string  The help text
 * @see     Oop_Drupal_Hooks::help
 */
function shell_help( $path, $arg )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'shell' )->help( $path, $arg );
}

function shell_menu()
{
    $module = Oop_Core_ClassManager::getInstance()->getModule( 'shell' );
    return $module->addMenuItems( $module->addAdminSettingsMenu() );
}

function shell_adminForm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'shell' )->getAdminForm();
}

function shell_adminForm_validate( $form, &$formState )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'shell' )->validateAdminForm( $form, $formState );
}

function shell_show()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'shell' )->createModuleContent( 'show' );
}

function shell_perm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'shell' )->perm();
}
