<?php

# $Id$

/**
 * Drupal 'help' hook
 * 
 * This function returns the help text for the admin/help# page. The label
 * returned must be placed in the module's lang file, in the 'lang/'
 * directory. It's the 'help' node of the 'system' section.
 * 
 * @param   string  The path for which to display help
 * @param   array   An array that holds the current path as would be returned from the arg() function
 * @return  string  The help text
 * @see     Oop_Drupal_Hooks::help
 */
function kickstarter_help( $path, $arg )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->help( $path, $arg );
}

function kickstarter_perm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->perm();
}

function kickstarter_menu()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->addMenuItems();
}

function kickstarter_show()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->createModuleContent( 'show' );
}

function kickstarter_form()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->getForm();
}

function kickstarter_form_validate( $form, &$formState )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->validateForm( $form, $formState );
}

function kickstarter_form_submit( $formId, $formValues )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->submitForm( $formId, $formValues );
}
