<?php

# $Id$

/**
 * Drupal 'help' hook
 * 
 * This function returns the help text for the admin/help# page. The label
 * returned must be placed in the module's lang file, in the 'lang/'
 * directory. It's the 'help' node of the 'system' section.
 * 
 * @param   string  The path for which to display help
 * @param   array   An array that holds the current path as would be returned from the arg() function
 * @return  string  The help text
 * @see     Oop_Drupal_Hooks::help
 */
function kickstarter_help( $path, $arg )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->help( $path, $arg );
}

/**
 * Drupal 'perm' hook
 * 
 * This function returns the available permissions for the module. They must
 * be declared in the $_perm property of the module class.
 * 
 * @return  array   The permissions array
 * @see     Oop_Drupal_Hooks::perm
 */
function kickstarter_perm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->perm();
}

/**
 * Drupal 'menu' hook
 * 
 * This function lets Drupal know that the module has custom menu items.
 * An administration settings page will be automatically added if the file
 * 'settings/admin.form.php' exists.
 * 
 * @return  array   An array with the menu items
 * @see     Oop_Drupal_Hooks::menu
 */
function kickstarter_menu()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->menu();
}

/**
 * Displays the page for a menu item
 * 
 * This function generates the content for a page placed in a custom menu item
 * 
 * @return  string  The content of the page
 * @see     Oop_Drupal_Hooks::menu
 * @see     Oop_Drupal_Hooks::createModuleContent
 */
function kickstarter_show()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->createModuleContent( 'show' );
}

/**
 * Drupal 'form' hook
 * 
 * This function returns the form configuration for the node creation/ edition.
 * The form configuration must be defined in the 'settings/node.form.php' file.
 * 
 * @param   stdClass    The node object
 * @return  array       An array with the form configuration
 * @see     Oop_Drupal_Hooks::form
 */
function kickstarter_form()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->getForm();
}

/**
 * Validates the kickstarter form
 * 
 * This function will be called when the kickstarter form is submitted.
 * 
 * @param   array   The form configuration
 * @param   array   The submitted values
 * @return  NULL
 * @see     kickstarter::validateAdminForm
 */
function kickstarter_form_validate( $form, &$formState )
{
    Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->validateForm( $form, $formState );
}

/**
 * Submits the admin form
 * 
 * This function will be called when the form kickstarter is submitted and
 * validated. It will create the module files.
 * 
 * @param   array   The form configuration
 * @param   array   The submitted values
 * @return  NULL
 * @see     kickstarter::submitForm
 */
function kickstarter_form_submit( $formId, $formValues )
{
    Oop_Core_ClassManager::getInstance()->getModule( 'kickstarter' )->submitForm( $formId, $formValues );
}
