<?php

# $Id$

function googlesitemap_help( $path, $arg )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'googlesitemap' )->help( $path, $arg );
}

function googlesitemap_menu()
{
    $module = Oop_Core_ClassManager::getInstance()->getModule( 'googlesitemap' );
    return $module->addMenuItems( $module->addAdminSettingsMenu() );
}

function googlesitemap_adminForm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'googlesitemap' )->getAdminForm();
}

function googlesitemap_show()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'googlesitemap' )->createModuleContent( 'show' );
}
