<?php

# $Id$

/**
 * Drupal 'help' hook
 * 
 * This function returns the help text for the admin/help# page. The label
 * returned must be placed in the module's lang file, in the 'lang/'
 * directory. It's the 'help' node of the 'system' section.
 * 
 * @param   string  The path for which to display help
 * @param   array   An array that holds the current path as would be returned from the arg() function
 * @return  string  The help text
 * @see     Oop_Drupal_Hooks::help
 */
function ddsitemap_help( $path, $arg )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->help( $path, $arg );
}

function ddsitemap_perm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->perm();
}

function ddsitemap_menu()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->addAdminSettingsMenu();
}

function ddsitemap_adminForm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->getAdminForm();
}

function ddsitemap_access( $op, $node, $account )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->access( $op, $node, $account );
}

function ddsitemap_form( stdClass $node )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->form( $node );
}

function ddsitemap_node_info()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->node_info();
}

function ddsitemap_view( stdClass $node, $teaser = false, $page = false )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->view( $node, $teaser, $page );
}

function ddsitemap_insert( stdClass $node )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->insert( $node );
}

function ddsitemap_update( stdClass $node )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddsitemap' )->update( $node );
}
