<?php

# $Id$

Oop_Core_ClassManager::getInstance()->getModule( 'ddmenu' )->setNumberOfBlocks( Oop_Drupal_Utils::getInstance()->getModuleVariable( 'oop', 'number_of_blocks', 1 ), true );

function ddmenu_help( $path, $arg )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddmenu' )->help( $path, $arg );
}

function ddmenu_perm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddmenu' )->perm();
}

function ddmenu_block( $op = 'list', $delta = 0, array $edit = array() )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddmenu' )->block( $op, $delta, $edit );
}

function ddmenu_menu()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddmenu' )->addAdminSettingsMenu();
}

function ddmenu_adminForm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddmenu' )->getAdminForm();
}

function ddmenu_adminForm_validate( $form, &$formState )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'ddmenu' )->validateAdminForm( $form, $formState );
}
