<?php

# $Id$

/**
 * Drupal 'help' hook
 * 
 * This function returns the help text for the admin/help# page. The label
 * returned must be placed in the module's lang file, in the 'lang/'
 * directory. It's the 'help' node of the 'system' section.
 * 
 * @param   string  The path for which to display help
 * @param   array   An array that holds the current path as would be returned from the arg() function
 * @return  string  The help text
 * @see     Oop_Drupal_Hooks::help
 */
function emailcrypt_help( $path, $arg )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'emailcrypt' )->help( $path, $arg );
}

function emailcrypt_filter( $op, $delta = 0, $format = -1, $text = '' )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'emailcrypt' )->filter( $op, $delta, $format, $text );
}
