<?php

function helloworld_help( $path, $arg )
{
    return Core_ClassManager::getInstance()->getModule( 'helloworld' )->help( $path, $arg );
}

function helloworld_perm()
{
    return Core_ClassManager::getInstance()->getModule( 'helloworld' )->perm();
}

function helloworld_block( $op = 'list', $delta = 0 )
{
    return Core_ClassManager::getInstance()->getModule( 'helloworld' )->block( $op, $delta );
}
