<?php

# $Id$

function foo_help( $path, $arg )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'foo' )->help( $path, $arg );
}

function foo_perm()
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'foo' )->perm();
}

function foo_block( $op = 'list', $delta = 0, array $edit = array() )
{
    return Oop_Core_ClassManager::getInstance()->getModule( 'foo' )->block( $op, $delta, $edit );
}
